### ISSUE TITLE
Any option to set install path?

### ISSUE THREAD

**Issue by SrKomodo** [itchio/itch-setup#8]
I would like to install itch.io to a path different from `~/.itch`. Is this possible right now, and if not, would it be easy to implement this feature?

**Comment by fasterthanlime** [comment]
It's not possible right now, and adding configurable installation paths would add a bunch of complexity - both to the installation process (more - blocking - steps for the user) and to the launch process (find config file first).

However, this isn't as big a deal as it sound because:

  * Most of the space is taken by content (games installed with itch), and you can change the default install location for these from the app
  * On Linux, you can move `~/.itch` to anywhere else, and use a symbolic link from `~/.itch` to your new location - if you really insist on having the ~200MB somewhere else.

**Comment by SrKomodo** [comment]
Alright then. Thanks!
